# Generated by Django 6.0.7 on 2026-07-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_must_change_password_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Team Member Account', 'verbose_name_plural': 'Team Member Accounts'},
        ),
    ]
